version: '3.1'

services:
  chat_system_db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  php_my_admin_interface:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: chat_system_db
      MYSQL_ROOT_PASSWORD: rootpassword
    depends_on:
      - chat_system_db

  redis_db:
    image: redis:latest
    container_name: redis_db
    ports:
      - "6379:6379" # Expose Redis on port 6379 on your host
    networks:
      - backend
    volumes:
      - ./redis_data:/data # Persist data

  redis-commander-interface:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander-interface
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081" # Redis Commander will be available on port 8081 on your host
    networks:
      - backend
    depends_on:
      - redis_db

networks:
  backend:
    driver: bridge

volumes:
  redis_data:
  mysql_data:
